### ISSUE TITLE
Suggestion: use CustomOperations to reduce use of yield

### ISSUE THREAD

**Issue by panesofglass** [rspeele/LicenseToCIL#2]
You should be able to reduce the use of `yield` by using the [`CustomOperationAttribute`](https://msdn.microsoft.com/visualfsharpdocs/conceptual/core.customoperationattribute-class-%5bfsharp%5d) for each of the IL terms. There's an example of this in a Community for F# talk from 2012: [Computation Expressions in F# 3.0](https://vimeo.com/47218436).

**Comment by rspeele** [comment]
I have experimented with this a bit, and while I definitely like the look of the `cil` blocks without `yield yield yield` everywhere, I remember it having one big downside: it prevents the use of `if/then/else` blocks.

Edit: found the error I was thinking of, it's [FS3086](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSComp.txt#L1206)

I like having the ability to conditionally generate different IL with the same stack transition behavior, as demonstrated in the `defaultOfType` function in the README.
